=== BigBlackFella/IRIS/interaction-commands-mule/src/test/resources/Metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://iris.temenos.com/metadata.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Metadata" type="met:MetadataType" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
  <xs:complexType name="PropertyType" mixed="true">
    <xs:sequence>
      <xs:element type="met:TermType" name="Term" maxOccurs="unbounded" minOccurs="0" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
      <xs:element type="met:PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="Name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="TermType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="MetadataType">
    <xs:sequence>
      <xs:element type="met:EntityType" name="Entity" maxOccurs="unbounded" minOccurs="0" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="ModelName"/>
    <xs:attribute type="xs:float" name="Version"/>
  </xs:complexType>
  <xs:complexType name="EntityType">
    <xs:sequence>
      <xs:element type="met:PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="Name" use="optional"/>
  </xs:complexType>
</xs:schema>

=== BigBlackFella/IRIS/interaction-dsl/interaction-translate/src/it/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  #%L
  interaction-example-odata-notes
  %%
  Copyright (C) 2012 - 2013 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->

<Metadata ModelName="InteractionNote" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
    <Entity Name="ServiceDocument"></Entity>
    <Entity Name="Metadata"></Entity>
    <Entity Name="Note">
        <Property Name="id">
            <Term Name="TERM_MANDATORY">true</Term>
            <Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
            <Term Name="TERM_ID_FIELD">true</Term>
        </Property>
        <Property Name="body">
            <Term Name="TERM_MANDATORY">false</Term>
            <Term Name="TERM_VALUE_TYPE">STRING</Term>
        </Property>
        <Property Name="personId" />
    </Entity>
	<Entity Name="Person">
        <Property Name="id">
            <Term Name="TERM_MANDATORY">true</Term>
            <Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
            <Term Name="TERM_ID_FIELD">true</Term>
        </Property>
        <Property Name="name">
            <Term Name="TERM_MANDATORY">false</Term>
            <Term Name="TERM_VALUE_TYPE">STRING</Term>
        </Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-examples/interaction-odata-northwind/src/main/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<Metadata ModelName="Northwind" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="Suppliers">
		<Property Name="HomePage" />
		<Property Name="ContactName" />
		<Property Name="Phone" />
		<Property Name="ContactTitle" />
		<Property Name="Country" />
		<Property Name="Fax" />
		<Property Name="Address" />
		<Property Name="CompanyName">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="City" />
		<Property Name="PostalCode" />
		<Property Name="SupplierID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="Region" />
	</Entity>
	<Entity Name="Orders">
		<Property Name="EmployeeID">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="ShipName" />
		<Property Name="CustomerID" />
		<Property Name="ShipVia">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="OrderDate">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="ShipCity" />
		<Property Name="RequiredDate">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="OrderID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="ShipCountry" />
		<Property Name="ShipRegion" />
		<Property Name="ShipPostalCode" />
		<Property Name="Freight">
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
		<Property Name="ShipAddress" />
		<Property Name="ShippedDate">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
	</Entity>
	<Entity Name="Order_Details">
		<Property Name="OrderID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="ProductID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="Discount">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
		<Property Name="UnitPrice">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
		<Property Name="Quantity">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
	</Entity>
	<Entity Name="Customers">
		<Property Name="ContactTitle" />
		<Property Name="ContactName" />
		<Property Name="City" />
		<Property Name="Fax" />
		<Property Name="CompanyName">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="Address" />
		<Property Name="CustomerID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="Region" />
		<Property Name="Country" />
		<Property Name="Phone" />
		<Property Name="PostalCode" />
	</Entity>
	<Entity Name="Categories">
		<Property Name="CategoryID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="CategoryName">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="Description" />
		<Property Name="Picture" />
	</Entity>
	<Entity Name="Employees">
		<Property Name="Country" />
		<Property Name="PostalCode" />
		<Property Name="Region" />
		<Property Name="ReportsTo">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="LastName">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="Notes" />
		<Property Name="HireDate">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="PhotoPath" />
		<Property Name="EmployeeID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="Photo" />
		<Property Name="FirstName">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="HomePhone" />
		<Property Name="City" />
		<Property Name="Address" />
		<Property Name="TitleOfCourtesy" />
		<Property Name="BirthDate">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="Extension" />
		<Property Name="Title" />
	</Entity>
	<Entity Name="Products">
		<Property Name="ProductName">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="UnitPrice">
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
		<Property Name="QuantityPerUnit" />
		<Property Name="ProductID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="ReorderLevel">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="CategoryID">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="SupplierID">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="Discontinued">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">BOOLEAN</Term>
		</Property>
		<Property Name="UnitsInStock">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="UnitsOnOrder">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-media-odata-xml/src/test/resources/metadata-T24FieldMetadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  interaction-media-odata-xml
  %%
  Copyright (C) 2012 - 2015 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->
		
<Metadata ModelName="CustomerServiceTest" Version="1.0" 
		xmlns="http://iris.temenos.com/metadata.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="T24FieldMetadata">
		<Property Name="Id">
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="Entity" />
		<Property Name="Property" />
		<Property Name="Visible" />
		<Property Name="Mandatory" />
		<Property Name="MandatorySelection" />
		<Property Name="ReadOnly" />
		<Property Name="EnrichmentsMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="valuePosition" />
			<Property Name="subValuePosition" />
			<Property Name="FieldNumber" />
			<Property Name="FieldValue" />
			<Property Name="Enrichment" />
		</Property>
		<Property Name="PossibleValuesMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="valuePosition" />
			<Property Name="subValuePosition" />
			<Property Name="Value" />
			<Property Name="Description" />
		</Property>
		<Property Name="AAPropertiesMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="valuePosition" />
			<Property Name="subValuePosition" />
			<Property Name="T24AppVersion" />
			<Property Name="PropertyClassDecription" />
			<Property Name="PropertyDecription" />
			<Property Name="ForwardDateable" />
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-examples/interaction-hateoas-restbucks/src/main/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<Metadata ModelName="Restbucks" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
    <Entity Name="ServiceDocument"></Entity>
    <Entity Name="Metadata"></Entity>
	<Entity Name="Order">
		<Property Name="Id">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="location" />
		<Property Name="name" />
		<Property Name="milk" />
		<Property Name="quantity">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="size" />
	</Entity>
	<Entity Name="Payment">
		<Property Name="Id">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="authorisationCode" />
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-examples/interaction-odata-embedded/src/main/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  #%L
  interaction-example-odata-embedded
  %%
  Copyright (C) 2012 - 2014 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->

<Metadata ModelName="interaction-odata-embedded" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
    <Entity Name="ServiceDocument"></Entity>
    <Entity Name="Metadata"></Entity>
	<Entity Name="Airport">
		<Property Name="name">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="code">
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="country">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
	</Entity>
	<Entity Name="Flight">
		<Property Name="flightID">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="flightScheduleNum">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="takeoffTime">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
	</Entity>
	<Entity Name="FlightSchedule">
		<Property Name="flightNo">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="arrivalAirportCode">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="arrivalTime">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIME</Term>
		</Property>
		<Property Name="departureTime">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIME</Term>
		</Property>
		<Property Name="departureAirportCode">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="flightScheduleID">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="firstDeparture">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="lastDeparture">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
	</Entity>
	<Entity Name="Passenger">
		<Property Name="dateOfBirth">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="passengerNo">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="flightID">
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="name">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-examples/interaction-hateoas-banking/src/main/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<Metadata ModelName="HateoasBanking" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="Preferences">
		<Property Name="userID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="currency">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="language" />
	</Entity>
	<Entity Name="FundsTransfer">
		<Property Name="id">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="body" >
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
	</Entity>
	<Entity Name="Customer">
		<Property Name="name" >
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="address">
			<Property Name="number">
				<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			</Property>
			<Property Name="postCode" />
		</Property>
		<Property Name="dateOfBirth" >
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-media-odata-xml/src/test/resources/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  interaction-media-odata-xml
  %%
  Copyright (C) 2012 - 2013 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->
		
<Metadata ModelName="hothouse-models" Version="1.0" 
		xmlns="http://iris.temenos.com/metadata.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="Teller_Cashinl">
		<Property Name="TransactionNumber">
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="Customer2" />
		<Property Name="Currency1" />
		<Property Name="Account1MvGroup">
			<Property Name="AmountLocal1" />
			<Property Name="Account1" />
		</Property>
		<Property Name="Account2" />
		<Property Name="ValueDate2" />
		<Property Name="Narrative2MvGroup">
			<Property Name="Narrative2" />
		</Property>
		<Property Name="NetAmount" />
		<Property Name="DrCrMarker" />
		<Property Name="WaiveCharges" />
		<Property Name="TransactionCode" />
		<Property Name="NewCustBalMvGroup">
			<Property Name="NewCustBal" />
		</Property>
		<Property Name="DrDenomMvGroup">
			<Property Name="DrDenom" />
			<Property Name="DrUnit" />
		</Property>
		<Property Name="OverrideMvGroup">
			<Property Name="Override" />
		</Property>
		<Property Name="RecordStatus" />
		<Property Name="CurrNo" />
		<Property Name="InputterMvGroup">
			<Property Name="Inputter" />
		</Property>
		<Property Name="DateTimeMvGroup">
			<Property Name="DateTime" />
		</Property>
		<Property Name="Authoriser" />
		<Property Name="CoCode" />
		<Property Name="DeptCode" />
		<Property Name="AuditorCode" />
		<Property Name="AuditDateTime" />
	</Entity>
	<Entity Name="Customer">
		<Property Name="name" >
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="address">
			<Property Name="number">
				<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			</Property>
			<Property Name="street">
				<Property Name="streetType" />
			</Property>
			<Property Name="town" />
			<Property Name="postCode" />
		</Property>
		<Property Name="dateOfBirth" >
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="sector" />
		<Property Name="industry" />
		<Property Name="loyal" >
			<Term Name="TERM_VALUE_TYPE">BOOLEAN</Term>
		</Property>
		<Property Name="loyalty_rating" >
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-odata4j-ext/src/test/resources/issue126_metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  #%L
  interaction-odata4j-ext
  %%
  Copyright (C) 2012 - 2013 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->

<Metadata ModelName="CustomerServiceTest" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="Customer">
		<Property Name="name" >
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="address">
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
		</Property>
		<Property Name="number">
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="street">
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
		</Property>
		<Property Name="streetType">
			<Term Name="TERM_COMPLEX_GROUP">street</Term>
		</Property>
		<Property Name="town" >
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
		</Property>
		<Property Name="postCode" >
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
		</Property>
		<Property Name="dateOfBirth" >
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="sector" />
		<Property Name="industry" />
		<Property Name="loyal" >
			<Term Name="TERM_VALUE_TYPE">BOOLEAN</Term>
		</Property>
		<Property Name="loyalty_rating" >
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
	</Entity>
	<Entity Name="CustomerWithTermList">
		<Property Name="name" >
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="address">
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
			<Term Name="TERM_LIST_TYPE">true</Term>
		</Property>
		<Property Name="number">
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="street">
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
			<Term Name="TERM_LIST_TYPE">true</Term>
		</Property>
		<Property Name="streetType" >
			<Term Name="TERM_COMPLEX_GROUP">street</Term>
		</Property>
		<Property Name="streetName" >
			<Term Name="TERM_COMPLEX_GROUP">street</Term>
		</Property>
		<Property Name="town" >
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
		</Property>
		<Property Name="postCode" >
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
		</Property>
		<Property Name="dateOfBirth" >
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="sector" />
		<Property Name="industry" />
		<Property Name="loyal" >
			<Term Name="TERM_VALUE_TYPE">BOOLEAN</Term>
		</Property>
		<Property Name="loyalty_rating" >
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
	</Entity>
</Metadata>
