=== BigBlackFella/IRIS/interaction-commands-mule/src/test/resources/Metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://iris.temenos.com/metadata.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Metadata" type="met:MetadataType" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
  <xs:complexType name="PropertyType" mixed="true">
    <xs:sequence>
      <xs:element type="met:TermType" name="Term" maxOccurs="unbounded" minOccurs="0" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
      <xs:element type="met:PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="Name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="TermType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Name" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="MetadataType">
    <xs:sequence>
      <xs:element type="met:EntityType" name="Entity" maxOccurs="unbounded" minOccurs="0" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="ModelName"/>
    <xs:attribute type="xs:float" name="Version"/>
  </xs:complexType>
  <xs:complexType name="EntityType">
    <xs:sequence>
      <xs:element type="met:PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0" xmlns:met="http://iris.temenos.com/metadata.xsd"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="Name" use="optional"/>
  </xs:complexType>
</xs:schema>

=== BigBlackFella/IRIS/interaction-odata4j-ext/src/test/resources/metadata-oentity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  interaction-odata4j-ext
  %%
  Copyright (C) 2012 - 2014 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->
		
<Metadata ModelName="hothouse-models" Version="1.0" 
		xmlns="http://iris.temenos.com/metadata.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="oentity">
		<Property Name="ID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="FirstName"/>
		<Property Name="LastName"/>
		<Property Name="Address">			
			<Property Name="Number">
				<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			</Property>
			<Property Name="Road"/>
			<Property Name="Town" />
			<Property Name="County" />
		</Property>
	</Entity>
</Metadata>

<!-- 
		<Property Name="address">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="number">
				<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			</Property>
			<Property Name="street">
				<Term Name="TERM_LIST_TYPE">true</Term>
				<Property Name="streetType" />
			</Property>
			<Property Name="town" />
			<Property Name="postCode" />
		</Property>

 -->

=== BigBlackFella/IRIS/interaction-examples/T24-ft-interaction-banking/src/main/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<Metadata Version="1.0" xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="FundsTransfer">
		<Property Name="Id">
			<Term Name="TERM_ID_FIELD">true</Term>
			<Term Name="TERM_VALUE_TYPE">TEXT</Term>
		</Property>
		<Property Name="TransactionType">
			<Term Name="TERM_VALUE_TYPE">TEXT</Term>
		</Property>
		<Property Name="DebitAcctNo">
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
		<Property Name="DebitCurrency">
			<Term Name="TERM_VALUE_TYPE">TEXT</Term>
		</Property>
		<Property Name="DebitAmount">
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
		<Property Name="CreditAcctNo">
			<Term Name="TERM_VALUE_TYPE">TEXT</Term>
		</Property>
		<Property Name="RecordStatus">
			<Term Name="TERM_VALUE_TYPE">TEXT</Term>
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-media-odata-xml/src/test/resources/metadata-FtCommissionType.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  interaction-media-odata-xml
  %%
  Copyright (C) 2012 - 2014 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->
		
<Metadata ModelName="hothouse-models" Version="1.0" 
		xmlns="http://iris.temenos.com/metadata.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="FtCommissionType">
		<Property Name="CommissionType">
			<Term Name="TERM_ID_FIELD">true</Term>
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_SEMANTIC_TYPE">A</Term>
		</Property>
		<Property Name="DescriptionMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Term Name="TERM_LANG_TYPE">true</Term>
			<Property Name="LanguageCode" />
			<Property Name="Description">
				<Term Name="TERM_MANDATORY">true</Term>
				<Term Name="TERM_SEMANTIC_TYPE">A</Term>
			</Property>
		</Property>
		<Property Name="ShortDescrMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Term Name="TERM_LANG_TYPE">true</Term>
			<Property Name="LanguageCode" />
			<Property Name="ShortDescr">
				<Term Name="TERM_MANDATORY">true</Term>
				<Term Name="TERM_SEMANTIC_TYPE">A</Term>
			</Property>
		</Property>
		<Property Name="CcyConvDependent" />
		<Property Name="CategoryAccount">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_SEMANTIC_TYPE">A</Term>
		</Property>
		<Property Name="TxnCodeCr">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="TxnCodeDr">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="TaxCode">
			<Term Name="TERM_SEMANTIC_TYPE">A</Term>
		</Property>
		<Property Name="CalculationBasis" />
		<Property Name="CurrencyMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="Currency">
				<Term Name="TERM_SEMANTIC_TYPE">CCY</Term>
			</Property>
			<Property Name="FlatAmt">
				<Term Name="TERM_SEMANTIC_TYPE">AMT</Term>
			</Property>
			<Property Name="CalcTypeSvGroup">
				<Term Name="TERM_LIST_TYPE">true</Term>
				<Property Name="CalcType" />
				<Property Name="Percentage">
					<Term Name="TERM_SEMANTIC_TYPE">R</Term>
				</Property>
				<Property Name="UnitCharge">
					<Term Name="TERM_SEMANTIC_TYPE">AMT</Term>
				</Property>
				<Property Name="UptoAmt">
					<Term Name="TERM_SEMANTIC_TYPE">AMT</Term>
				</Property>
				<Property Name="MinimumAmt">
					<Term Name="TERM_SEMANTIC_TYPE">AMT</Term>
				</Property>
				<Property Name="MaximumAmt">
					<Term Name="TERM_SEMANTIC_TYPE">AMT</Term>
				</Property>
			</Property>
			<Property Name="RoundType" />
			<Property Name="RoundUnit">
				<Term Name="TERM_SEMANTIC_TYPE">R</Term>
			</Property>
			<Property Name="OverallMinPct">
				<Term Name="TERM_SEMANTIC_TYPE">R</Term>
			</Property>
			<Property Name="OverallMaxPct">
				<Term Name="TERM_SEMANTIC_TYPE">R</Term>
			</Property>
			<Property Name="OverallMinAmt">
				<Term Name="TERM_SEMANTIC_TYPE">AMT</Term>
			</Property>
			<Property Name="OverallMaxAmt">
				<Term Name="TERM_SEMANTIC_TYPE">AMT</Term>
			</Property>
			<Property Name="AccrualMinAmt">
				<Term Name="TERM_SEMANTIC_TYPE">AMT</Term>
			</Property>
		</Property>
		<Property Name="MthlyAmortisation" />
		<Property Name="AmortisnPeriod">
			<Term Name="TERM_SEMANTIC_TYPE">A</Term>
		</Property>
		<Property Name="ChargePeriod" />
		<Property Name="MinimumPeriod" />
		<Property Name="ResidencyMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="Residency">
				<Term Name="TERM_SEMANTIC_TYPE">A</Term>
			</Property>
		</Property>
		<Property Name="NonResidencyMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="NonResidency">
				<Term Name="TERM_SEMANTIC_TYPE">A</Term>
			</Property>
		</Property>
		<Property Name="LinkMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="Link">
				<Term Name="TERM_SEMANTIC_TYPE">A</Term>
			</Property>
		</Property>
		<Property Name="NextDateMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="NextDate" />
		</Property>
		<Property Name="AccrualFqu" />
		<Property Name="AccrueAmort" />
		<Property Name="SwiftNarr">
			<Term Name="TERM_SEMANTIC_TYPE">S</Term>
		</Property>
		<Property Name="DefaultCcy">
			<Term Name="TERM_SEMANTIC_TYPE">CCY</Term>
		</Property>
		<Property Name="ChargeRoutine">
			<Term Name="TERM_SEMANTIC_TYPE">A</Term>
		</Property>
		<Property Name="ExcludeFromEir" />
		<Property Name="Reserved2" />
		<Property Name="Reserved1" />
		<Property Name="OverrideMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="Override">
				<Term Name="TERM_SEMANTIC_TYPE">A</Term>
			</Property>
		</Property>
		<Property Name="RecordStatus">
			<Term Name="TERM_SEMANTIC_TYPE">STAT</Term>
		</Property>
		<Property Name="CurrNo" />
		<Property Name="InputterMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="Inputter">
				<Term Name="TERM_SEMANTIC_TYPE">A</Term>
			</Property>
		</Property>
		<Property Name="DateTimeMvGroup">
			<Term Name="TERM_LIST_TYPE">true</Term>
			<Property Name="DateTime">
				<Term Name="TERM_SEMANTIC_TYPE">RELTIME</Term>
			</Property>
		</Property>
		<Property Name="Authoriser">
			<Term Name="TERM_SEMANTIC_TYPE">A</Term>
		</Property>
		<Property Name="CoCode">
			<Term Name="TERM_SEMANTIC_TYPE">A</Term>
		</Property>
		<Property Name="DeptCode" />
		<Property Name="AuditorCode">
			<Term Name="TERM_SEMANTIC_TYPE">A</Term>
		</Property>
		<Property Name="AuditDateTime">
			<Term Name="TERM_SEMANTIC_TYPE">RELTIME</Term>
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-examples/interaction-hateoas-simple/src/main/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  #%L
  interaction-example-hateoas-simple
  %%
  Copyright (C) 2012 - 2013 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->

<Metadata ModelName="HateoasSimple" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
    <Entity Name="HOME"></Entity>
    <Entity Name="ID"></Entity>
	<Entity Name="Profile">
		<Property Name="userID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="name">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="DOB">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="location" />
		<Property Name="pictureTaken">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
	</Entity>
	<Entity Name="Preferences">
		<Property Name="userID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="currency">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="language" />
	</Entity>
	<Entity Name="Note">
		<Property Name="noteID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="body" >
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-examples/interaction-mashup-twitter/src/main/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  #%L
  interaction-example-mashup-twitter
  %%
  Copyright (C) 2012 - 2013 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->

<Metadata ModelName="MashupTwitter" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
    <Entity Name="home"></Entity>
	<Entity Name="User">
		<Property Name="userID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="fullName">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="twitterHandle" />
	</Entity>
	<Entity Name="Tweet">
		<Property Name="username">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="message">
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="geolocation" />
	</Entity>
    <Entity Name="Timeline">
        <Property Name="tweet">
            <Term Name="TERM_MANDATORY">true</Term>
            <Term Name="TERM_ID_FIELD">true</Term>
        </Property>
    </Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-sdk/src/test/resources/Banking.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  #%L
  interaction-sdk
  %%
  Copyright (C) 2012 - 2013 Temenos Holdings N.V.
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->

<Metadata ModelName="Banking" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="Sector">
		<Property Name="Authoriser" />
		<Property Name="DeptCode" />
		<Property Name="Description">
			<Term Name="TERM_COMPLEX_GROUP">DescriptionMvGroup</Term>
		</Property>
		<Property Name="RecordStatus" />
		<Property Name="RiskExpoType" />
		<Property Name="AuditDateTime">
			<Term Name="TERM_VALUE_TYPE">DATE</Term>
		</Property>
		<Property Name="ShortNameMvGroup">
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
		</Property>
		<Property Name="Reserved1" />
		<Property Name="Reserved3" />
		<Property Name="SectorCode">
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="Reserved2" />
		<Property Name="CoCode" />
		<Property Name="Reserved4" />
		<Property Name="CurrNo" />
		<Property Name="DateTime">
			<Term Name="TERM_COMPLEX_GROUP">DateTimeMvGroup</Term>
		</Property>
		<Property Name="Inputter">
			<Term Name="TERM_COMPLEX_GROUP">InputterMvGroup</Term>
		</Property>
		<Property Name="ShortName">
			<Term Name="TERM_COMPLEX_GROUP">ShortNameMvGroup</Term>
		</Property>
		<Property Name="InputterMvGroup">
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
		</Property>
		<Property Name="DateTimeMvGroup">
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
		</Property>
		<Property Name="DescriptionMvGroup">
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
		</Property>
		<Property Name="AuditorCode" />
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-examples/interaction-odata-airline/src/main/resources/metadata.xml
<?xml version="1.0" encoding="utf-8"?>
<Metadata ModelName="FlightResponder" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
    <Entity Name="ServiceDocument"></Entity>
    <Entity Name="Metadata"></Entity>
	<Entity Name="Exception">
		<Property Name="code" >
			<Term Name="TERM_MANDATORY">true</Term>
		</Property>
		<Property Name="errorMessage" />
	</Entity>
	<Entity Name="FlightSchedule">
		<Property Name="flightNo" />
		<Property Name="arrivalAirportCode" />
		<Property Name="arrivalTime">
			<Term Name="TERM_VALUE_TYPE">TIME</Term>
		</Property>
		<Property Name="departureTime">
			<Term Name="TERM_VALUE_TYPE">TIME</Term>
		</Property>
		<Property Name="departureAirportCode" />
		<Property Name="flightScheduleID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="firstDeparture">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="lastDeparture">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
	</Entity>
	<Entity Name="Airport">
		<Property Name="name" />
		<Property Name="code">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="country" />
	</Entity>
	<Entity Name="Flight">
		<Property Name="flightID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="flightScheduleNum">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="takeoffTime">
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
	</Entity>
	<Entity Name="Passenger">
		<Property Name="passengerNo">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="flightID">
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="name" />
		<Property Name="dateOfBirth" >
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<!-- Property Name="address">
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
		</Property>
		<Property Name="number">
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
			<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
		</Property>
		<Property Name="street">
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
			<Term Name="TERM_COMPLEX_TYPE">true</Term>
		</Property>
		<Property Name="streetType" >
			<Term Name="TERM_COMPLEX_GROUP">street</Term>
		</Property>
		<Property Name="town" >
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
		</Property>
		<Property Name="postCode" >
			<Term Name="TERM_COMPLEX_GROUP">address</Term>
		</Property-->
	</Entity>
</Metadata>
