=== BigBlackFella/IRIS/interaction-core/src/main/resources/metadata.xsd
<!-- IRIS metadata schema -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" 
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xmlns="http://iris.temenos.com/metadata.xsd"
   targetNamespace="http://iris.temenos.com/metadata.xsd">

  <xs:element name="Metadata" type="MetadataType" />

  <xs:complexType name="MetadataType">    
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Entity" type="EntityType" />
    </xs:sequence>
    <xs:attribute type="xs:float" name="Version"/>
  </xs:complexType>

  <xs:complexType name="EntityType">    
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Property" type="PropertyType" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="Name"/>
  </xs:complexType>

  <xs:complexType name="PropertyType">    
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Property" type="PropertyType" minOccurs="0" />
      <xs:element name="Term" type="TermType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="Name"/>
  </xs:complexType>

  <xs:complexType name="TermType">    
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Name"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== BigBlackFella/IRIS/interaction-core/src/test/resources/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>		
<Metadata ModelName="hothouse-models" Version="1.0" 
		xmlns="http://iris.temenos.com/metadata.xsd" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="Teller_Cashinl">
		<Property Name="TransactionNumber">
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="Customer2" />
		<Property Name="Currency1" />
		<Property Name="Account1MvGroup">
			<Property Name="AmountLocal1" />
			<Property Name="Account1" />
		</Property>
		<Property Name="Account2" />
		<Property Name="ValueDate2" />
		<Property Name="Narrative2MvGroup">
			<Property Name="Narrative2" />
		</Property>
		<Property Name="NetAmount" />
		<Property Name="DrCrMarker" />
		<Property Name="WaiveCharges" />
		<Property Name="TransactionCode" />
		<Property Name="NewCustBalMvGroup">
			<Property Name="NewCustBal" />
		</Property>
		<Property Name="DrDenomMvGroup">
			<Property Name="DrDenom" />
			<Property Name="DrUnit" />
		</Property>
		<Property Name="OverrideMvGroup">
			<Property Name="Override" />
		</Property>
		<Property Name="RecordStatus" />
		<Property Name="CurrNo" />
		<Property Name="InputterMvGroup">
			<Property Name="Inputter" />
		</Property>
		<Property Name="DateTimeMvGroup">
			<Property Name="DateTime" />
		</Property>
		<Property Name="Authoriser" />
		<Property Name="CoCode" />
		<Property Name="DeptCode" />
		<Property Name="AuditorCode" />
		<Property Name="AuditDateTime" />
	</Entity>
	<Entity Name="Customer">
		<Property Name="name" >
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="address">
			<Property Name="number">
				<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			</Property>
			<Property Name="street">
				<Property Name="streetType" />
			</Property>
			<Property Name="town" />
			<Property Name="postCode" />
		</Property>
		<Property Name="dateOfBirth" >
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="sector" />
		<Property Name="industry" />
		<Property Name="loyal" >
			<Term Name="TERM_VALUE_TYPE">BOOLEAN</Term>
		</Property>
		<Property Name="loyalty_rating" >
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
	</Entity>
</Metadata>

=== BigBlackFella/IRIS/interaction-core/src/test/resources/TestMetadataParser.xml
<?xml version="1.0" encoding="utf-8"?>
<Metadata ModelName="CustomerServiceTest" Version="1.0" 
          xmlns="http://iris.temenos.com/metadata.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://iris.temenos.com metadata.xsd">
	<Entity Name="Customer">
		<Property Name="name" >
			<Term Name="TERM_ID_FIELD">true</Term>
		</Property>
		<Property Name="address">
			<Property Name="number">
				<Term Name="TERM_VALUE_TYPE">INTEGER_NUMBER</Term>
			</Property>
			<Property Name="street">
				<Property Name="streetType" />
			</Property>
			<Property Name="town" />
			<Property Name="postCode" />
		</Property>
		<Property Name="dateOfBirth" >
			<Term Name="TERM_MANDATORY">true</Term>
			<Term Name="TERM_VALUE_TYPE">TIMESTAMP</Term>
		</Property>
		<Property Name="sector" />
		<Property Name="industry" />
		<Property Name="loyal" >
			<Term Name="TERM_VALUE_TYPE">BOOLEAN</Term>
		</Property>
		<Property Name="loyalty_rating" >
			<Term Name="TERM_VALUE_TYPE">NUMBER</Term>
		</Property>
	</Entity>
</Metadata>
